#!/bin/bash

set -e

normal=${1?}
early=${2?}
late=${3?}

log() {
	echo "$@" > /dev/stderr
}

wantdir="$normal/multi-user.target.wants"
mkdir -p "$wantdir"

for config in /etc/fetchmail-imap-idle.d/*.config ; do
	[ -f "$config" ] || continue
	basename="$(basename "$config")"
	conf_name="${basename%.config}"
	ln -s "/lib/systemd/system/fetchmail-imap-idle@.service" "${wantdir}/fetchmail-imap-idle@${conf_name}.service"

done
  
  
  
